PortfolioProject/PortfolioProject.UI/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Mvc;
using PortfolioProject.Business.Concrete;
using PortfolioProject.DataAccess.Concrete.EntityFramework;
using PortfolioProject.Entity.Concrete;

namespace PortfolioProject.UI.Controllers
{
    public class ServiceController : Controller
    {
        ServiceManager serviceManager = new ServiceManager(new EfServiceDal());

        public IActionResult Index()
        {
            var values = serviceManager.GetAll();
            return View(values);
        }

        [HttpGet]
        public IActionResult AddService()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddService(Service service)
        {
            serviceManager.Add(service);
            return RedirectToAction("Index");
        }
        public IActionResult DeleteService(int id)
        {
            var values = serviceManager.GetByID(id);
            serviceManager.Delete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditService(int id)
        {
            var values = serviceManager.GetByID(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult EditService(Service service)
        {
            serviceManager.Update(service);
            return RedirectToAction("Index");
        }
    }
}

PortfolioProject/PortfolioProject.UI/Views/Service/AddService.cshtml
@model Service

@{
    ViewData["Title"] = "AddService";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


@using (Html.BeginForm("AddService", "Service", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Hizmet Ekleme Paneli </p>
                <form class="forms-sample">
                    <br />
                    @Html.Label("Hizmet Başlığı")
                    @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                    <br />
                    <label>Resim Yolu</label>
                    @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
                    <br />
                    <button class="btn btn-outline-info">Kaydet</button>
                </form>
            </div>
        </div>
    </div>
}

PortfolioProject/PortfolioProject.UI/Views/Service/EditService.cshtml
@model Service

@{
    ViewData["Title"] = "EditService";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="card-header border-0">
    <h3 class="mb-0">Hizmet Düzenleme Sayfası</h3>
</div>
@using (Html.BeginForm("EditService", "Service", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Hizmet Ekleme Paneli </p>
                <form class="forms-sample">
                    @Html.HiddenFor(x => x.Id)
                    <br />
                    @Html.Label("Hizmet Başlığı")
                    @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                    <br />
                    <label>Resim Yolu</label>
                    @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
                    <br />
                    <button class="btn btn-outline-success">Güncelle</button>
                </form>
            </div>
        </div>
    </div>
}

PortfolioProject/PortfolioProject.UI/Views/Service/Index.cshtml
@model List<Service>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


<div class="card-header border-0">
    <h3 class="mb-0">Hizmet Listesi Tablosu</h3>
</div>
<!-- Light table -->
<div class="table-responsive">
    <table class="table align-items-center table-flush">
        <thead class="thead-light">
            <tr>
                <th scope="col" class="sort" data-sort="name">#</th>
                <th scope="col" class="sort" data-sort="budget">Başlık</th>
                <th scope="col">Sil</th>
                <th scope="col" class="sort" data-sort="completion">Düzenle</th>
            </tr>
        </thead>
        <tbody class="list">

            @foreach (var item in Model)
            {
                <tr>
                    <th>
                        @item.Id
                    </th>
                    <th class="budget">
                        @item.Title
                    </th>
                    <td><a href="/Service/DeleteService/@item.Id" class="btn btn-outline-danger">Sil</a></td>
                    <td><a href="/Service/EditService/@item.Id" class="btn btn-outline-info">Güncelle</a></td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    <a href="/Service/AddService/" class="btn btn-primary">Yeni Hizmet Ekle</a>
</div>