PortfolioProject/PortfolioProject.UI/Controllers/ExperienceController.cs
using Microsoft.AspNetCore.Mvc;
using PortfolioProject.Business.Concrete;
using PortfolioProject.DataAccess.Concrete.EntityFramework;
using PortfolioProject.Entity.Concrete;

namespace PortfolioProject.UI.Controllers
{
    public class ExperienceController : Controller
    {
        ExperienceManager experienceManager = new ExperienceManager(new EfExperienceDal());

        public IActionResult Index()
        {
            var values = experienceManager.GetAll();
            return View(values);
        }

        [HttpGet]
        public IActionResult AddExperience() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddExperience(Experience experience) 
        {
            experienceManager.Add(experience);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditExperience(int id) 
        {
            var entity = experienceManager.GetByID(id);
            return View(entity);   
        }

        [HttpPost]
        public IActionResult EditExperience(Experience experience)
        {
            experienceManager.Update(experience);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteExperience(int id)
        {
            var entity = experienceManager.GetByID(id);
            experienceManager.Delete(entity);
            return RedirectToAction("Index");
        }
    }
}

PortfolioProject/PortfolioProject.UI/Views/Experience/AddExperience.cshtml
@model Experience

@{
    ViewData["Title"] = "AddExperience";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


@using (Html.BeginForm("AddExperience", "Experience", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Yeni Deneyim Ekleme Paneli </p>
                <form class="forms-sample">
                    <div class="form-group">
                        <label>Başlık</label>
                        <input type="text" class="form-control" name="Name">
                    </div>
                    <div class="form-group">
                        <label>Tarih</label>
                        <input type="text" class="form-control" name="Date">
                    </div>
                    <div class="form-group">
                        <label>Görsel URL</label>
                        <input type="text" class="form-control" name="ImageUrl">
                    </div>

                    <div class="form-group">
                        <label>Açıklama</label>
                        <textarea class="form-control" name="Description" rows="6"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <button class="btn btn-dark">İptal</button>
                </form>
            </div>
        </div>
    </div>
}

PortfolioProject/PortfolioProject.UI/Views/Experience/EditExperience.cshtml
@model Experience

@{
    ViewData["Title"] = "EditExperience";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


@using (Html.BeginForm("EditExperience", "Experience", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Deneyim Düzenleme Paneli </p>
                <form class="forms-sample">
                    <div class="form-group">
                        <label>ID</label>
                        @Html.TextBoxFor(x => x.ID, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Başlık</label>
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Tarih</label>
                        @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Görsel URL</label>
                        @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <label>Açıklama</label>
                        @Html.TextAreaFor(x => x.Description, 6, 3, new { @class = "form-control" })
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <button class="btn btn-dark">İptal</button>
                </form>
            </div>
        </div>
    </div>
}

PortfolioProject/PortfolioProject.UI/Views/Experience/Index.cshtml
@model List<Experience>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Deneyimler</h4>

            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Başlık.</th>
                            <th>Tarih</th>
                            <th>Sil</th>
                            <th>Güncelle</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.ID</td>
                                <td>@item.Name</td>
                                <td>@item.Date</td>
                                <td><a href="/Experience/DeleteExperience/@item.ID" class="btn btn-outline-danger">Sil</a></td>
                                <td><a href="/Experience/EditExperience/@item.ID" class="btn btn-outline-success">Güncelle</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
                <a href="/Experience/AddExperience/" class="btn btn-outline-info">Yeni Deneyim Ekle</a>
            </div>
        </div>
    </div>
</div>